import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Truffle Butter Paneer',
    description: 'Cottage cheese simmered in a rich tomato gravy infused with black truffle oil.',
    price: 18,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 1,
    isVeg: true,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Smoked Dal Makhani',
    description: 'Black lentils cooked overnight with charcoal smoke finish and fresh cream.',
    price: 14,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 1,
    isVeg: true,
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Fiery Chicken Chettinad',
    description: 'A spicy South Indian curry made with roasted spices and coconut.',
    price: 22,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 3,
    isVeg: false,
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Gold Leaf Biryani',
    description: 'Aromatic basmati rice layered with saffron, marinated lamb, and edible gold leaf.',
    price: 35,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 2,
    isVeg: false,
    rating: 5.0,
  },
  {
    id: '5',
    name: 'Crispy Corn & Spinach',
    description: 'Tempura fried corn kernels tossed with spinach and asian spices.',
    price: 12,
    category: 'starter',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 1,
    isVeg: true,
    rating: 4.5,
  },
  {
    id: '6',
    name: 'Galouti Kebab',
    description: 'Melt-in-mouth minced meat kebabs served with ultra-soft saffron paratha.',
    price: 20,
    category: 'starter',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 2,
    isVeg: false,
    rating: 4.8,
  },
  {
    id: '7',
    name: 'Rose & Pistachio Kulfi',
    description: 'Traditional indian ice cream flavored with rose petals and roasted pistachios.',
    price: 10,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcf8?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 0,
    isVeg: true,
    rating: 4.9,
  },
  {
    id: '8',
    name: 'Saffron Lassi',
    description: 'Thick yogurt drink blended with saffron strands and cardamom.',
    price: 8,
    category: 'beverage',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80',
    spicyLevel: 0,
    isVeg: true,
    rating: 4.6,
  },
];